version: "3.3"

services:

## PostreSQL #######################################################################################
  postgres:
    image: iwaydev/yii2-iway-template-postgres:latest
    volumes:
      - ./docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5438:5432

## Nginx ###########################################################################################
  nginx:
    image: nginx:1.13.3
    networks:
        default:
            aliases:
            - yii2-iway-template.local
            - api.yii2-iway-template.local
            - site.yii2-iway-template.local
    ports:
      - 81:80
      - 448:443
    volumes:
      # Конфиг
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      # Логи
      - ./docker/logs:/var/log/nginx
      - ./docker/logs:/var/log/xdebug
      # Файлы
      - ./:/var/www/yii2-iway-template
    environment:
      NGINX_HOST: yii2-iway-template.local
      NGINX_HOST: site.yii2-iway-template.local
      NGINX_HOST: api.yii2-iway-template.local
      NGINX_PORT: 80
      NGINX_PORT: 443
    depends_on:
      - php

## PHP #############################################################################################
  php:
    image: iwaydev/yii2-iway-template-php-fpm:latest
    ports:
      - 9000
    environment:
      PHP_IDE_CONFIG: serverName=local
      XDEBUG_CONFIG: "remote_host=192.168.1.105"
    volumes:
      # Файлы
      - ./:/var/www/yii2-iway-template
      - ./docker/logs:/var/log/xdebug
      # Конфиг
      - ./docker/conf/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
      - redis
      - rabbitmq

## PHP daemon example ##############################################################################
#  php-simple-daemon:
#    image: iwaydev/yii2-iway-template-php-daemon-sample:latest
#    restart: always
#    environment:
#      PHP_IDE_CONFIG: serverName=local
#      XDEBUG_CONFIG: "remote_host=192.168.1.105"
#    volumes:
#      # Файлы
#      - ./:/var/www/yii2-iway-template
#      - ./docker/logs:/var/log/xdebug
#      # Конфиг
#      - ./docker/conf/php.ini:/usr/local/etc/php/php.ini
#    depends_on:
#      - postgres
#      - redis
#      - rabbitmq
#    deploy:
#      replicas: 10

## Redis ###########################################################################################
  redis:
    image: redis:3.2.9
    ports:
      - 6381:6379

## Rabbit ##########################################################################################
  rabbitmq:
    image: rabbitmq:3.6.10
    volumes:
      - ./docker/rabbitdb:/var/lib/rabbitmq
      - ./docker/rabbitmq.enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5676:5672
